version: '3.7'

services:
  browserless:
    image: browserless/chrome:latest
    environment:
      MAX_CONCURRENT_SESSIONS: 5
      CONNECTION_TIMEOUT: 30000

  app:
    image: ginette:latest
    build:
      context: .
    environment:
      TOKEN: ${TOKEN}
      BROWSERLESS_URL: http://browserless:3000
    ports:
      - '8080:8080'
    depends_on:
      - browserless
