let grandmaTexts = [
    "Bonjour ma CHOUETTE!! J'ai fait de la SOUPE aujourd'hui 🥣 c'est de la soupe aux LÉGUMES!! bisous Ginette xo",
    "ALLÔ!!!!! j'ai vu un CHAT dans la cour ce matin 🐱 il était GROS!! j'ai pris une photo mais je sais pas comment L'ENVOYER bisous Ginette",
    "Ma belle!! j'ai trouvé un BEAU chandail au Walmart SEULEMENT 12$!!!! 💃 je t'en ai ACHETÉ un aussi!! bisous Ginette xoxo",
    "Comment on fait pour enlever les MAJUSCULES sur mon téléphone??? Ton grand-père dit que je CRIE mais JE CRIE PAS bisous Ginette",
    "J'ai fait des BISCUITS 🍪🍪🍪 tu viens-tu SOUPER dimanche??? Pépère va faire du STEAK HACHÉ bisous Ginette xo",
    "BONNE JOURNÉE ma petite chouette D'AMOUR!!!! ☀️☀️☀️ il fait BEAU dehors!! Va jouer DEHORS!! bisous Ginette",
    "Ma belle!! j'ai vu ta PHOTO sur le Face Book!! T'es dont ben BELLE!! 😍😍😍 qui c'est à CÔTÉ??? bisous Ginette xo",
    "Oups j'ai ENVOYÉ ça à la mauvaise PERSONNE 😂😂 C'ÉTAIT POUR TON ONCLE RÉJEAN bisous Ginette",
    "J'ai essayé de faire un APPEL VIDÉO mais ça marchait PAS 😢 J'VOYAIS JUSTE MON FRONT bisous Ginette xo",
    "ATTENTION ma chouette!! il va NEIGER demain!! ❄️ Mets ta TUQUE pis tes MITAINES!! bisous Ginette xoxo",
    "Pépère a essayé de GOOGLER quelque chose pis il a écrit dans le FACE BOOK 😂😂😂 tout le monde a VU bisous Ginette",
    "Ma belle as-tu MANGÉ aujourd'hui??? tu manges-tu ASSEZ?? JE M'INQUIÈTE!! viens SOUPER!! ❤️ bisous Ginette xo",
    "J'ai acheté un CACTUS 🌵 Ginette d'à côté dit que c'est FACILE!! j'espère que je le TUERAI PAS comme le dernier bisous Ginette",
    "Ton oncle Roger a ENCORE pété la TONDEUSE 😤 3e FOIS cet été!! Ton grand-père est PAS CONTENT!! bisous Ginette xo",
    "Ma chouette!! j'ai appris à envoyer des ÉMOJIS!! 🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉 REGARDE!!!!! bisous Ginette",
    "J'AI GAGNÉ AU BINGO HIER SOIR!!! 🏆 42$!!! j'me suis payé un CAFÉ pis un BEIGNE au Tim 💃 bisous Ginette xoxo",
    "Bonjour mon TRÉSOR!! Mamie pense à TOI!! 💕 j'ai mis une CHANDELLE à l'église pour toi ce matin bisous Ginette xo",
    "Ton grand-père RONFLE tellement FORT 😴 je l'entends du SALON!!! ça fait 47 ANS que j'endure ça!! bisous Ginette",
    "J'AI TROUVÉ UNE RECETTE SUR LE GOOGLE!! c'est un gâteau aux CAROTTES 🥕 je vais l'essayer DEMAIN!! bisous Ginette xo",
    "Ma belle!! mon ÉMISSION commence dans 5 MINUTES!! 📺 on se reparle TANTÔT!! bisous Ginette xoxo",
    "C'est-tu TOI qui m'a envoyé un COURRIEL??? ton grand-père dit de PAS CLIQUER dessus 🤔 bisous Ginette xo",
    "J'ai ENCORE oublié mes LUNETTES au IGA 👓 c'est la 3e FOIS ce mois-ci!! SEIGNEUR!! bisous Ginette",
    "BONNE FÊTE ma chouette D'AMOUR!!!!! 🎂🎁🎈🎉 T'AS DONT BEN GRANDI!! ça passe VITE hein!! bisous Ginette xoxo",
    "Ton cousin Mathieu s'est fait une BLONDE!! 😱 elle s'appelle JESSICA!! elle a l'air FINE!! bisous Ginette xo",
    "J'ai planté des TOMATES 🍅🍅🍅 dans le jardin!! j'vais t'en APPORTER quand elles vont être PRÊTES!! bisous Ginette",
    "Pépère dit que l'INTERNET est CASSÉ mais je pense qu'il a juste DÉBRANCHÉ le fil encore 🙄 bisous Ginette xo",
    "Ma belle!! tu savais-tu que le petit TREMBLAY d'en face est DENTISTE maintenant??? MON DIEU que le temps PASSE!! bisous Ginette",
    "JOYEUSES PÂQUES 🐣🐰!! Mamie a fait des OEUFS EN CHOCOLAT!! y'en a un GROS pour toi!! bisous Ginette xoxo",
    "J'ai essayé le YOGA ce matin 🧘 mais j'me suis POGNÉE dans le tapis!! ton grand-père RIAIT!! bisous Ginette xo",
    "Comment ça VA ma chouette??? ça fait LONGTEMPS!! APPELLE-MOI des fois!! le téléphone marche dans les DEUX SENS!! 😘 bisous Ginette",
    "J'ai fait du SUCRE À CRÈME pour la visite!! 🍬 j'en ai TROP FAIT comme d'habitude!! Viens en CHERCHER!! bisous Ginette xo",
    "SEIGNEUR!! l'épicerie coûte CHER!! 😱 8$ pour du BEURRE!! dans MON TEMPS c'était 1$!! bisous Ginette",
    "Ton grand-père a essayé de RÉPARER la toilette 🔧 maintenant on a de l'eau PARTOUT!! j'ai appelé le PLOMBIER!! bisous Ginette xo",
    "Ma belle!! j'ai vu un DOCUMENTAIRE sur les pingouins 🐧!! savais-tu qu'ils DANSENT pour se réchauffer?? c'est CUTE!! bisous Ginette xoxo",
    "J'me suis faite une PERMANENTE aujourd'hui!! 💇 la coiffeuse dit que ça me RAJEUNIT!! qu'est-ce T'EN PENSES?? bisous Ginette xo",
    "Ton oncle a ENCORE acheté un CHAR USAGÉ 🚗 ton grand-père dit que c'est un CITRON!! Ha Ha!! bisous Ginette",
    "Ma chouette!! Mamie S'ENNUIE!! 🥺 viens-tu prendre un THÉ cette semaine??? j'ai des biscuits VILLAGE!! bisous Ginette xo",
    "IL PLEUT!! ☔️ j'espère que t'as ton PARAPLUIE!! tu vas attraper la GRIPPE sinon!! FAIS ATTENTION!! bisous Ginette xoxo",
    "J'ai appris que ça s'appelle un MÈME 😂😂 Pépère dit que c'est NIAISEUX mais MOI je trouve ça DRÔLE!! bisous Ginette xo",
    "QUELLE BELLE JOURNÉE!! ☀️ j'ai mis mes FLEURS sur le balcon!! les voisins sont JALOUX!! Ha Ha!! bisous Ginette",
    "Ma belle!! le chat de Ginette a eu des BÉBÉS!! 🐱🐱🐱 y'en a 6!! EN VEUX-TU UN??? bisous Ginette xo",
    "J'ai fait du PÂTÉ CHINOIS ce soir!! la RECETTE de ma mère!! personne le fait COMME NOUS AUTRES!! 💪 bisous Ginette xoxo",
    "Ton grand-père a perdu ses LUNETTES SUR SA TÊTE encore 😂😂 j'lui ai dit REGARDE EN HAUT!! bisous Ginette xo",
    "BONSOIR ma chouette!! Mamie va se COUCHER!! 🌙 fais de beaux RÊVES!! pense à APPELER demain!! bisous Ginette xoxo",
    "J'ai vu sur le FACE BOOK que t'as mangé au RESTAURANT!! 🍝 c'était-tu BON?? ça avait l'air CHER!! bisous Ginette xo",
    "Mon voisin m'a montré TIKTOK 📱 mais tout va TROP VITE!! je comprends RIEN!! c'est pour les JEUNES!! bisous Ginette",
    "J'ai trouvé un 2$ PAR TERRE au Canadian Tire!! 🤑 c'est ma JOURNÉE CHANCEUSE!! Ha Ha!! bisous Ginette xo",
    "Ma chouette!! fais-tu ton LAVAGE?? 👕 oublie PAS de séparer les COULEURS!! le blanc avec le BLANC!! bisous Ginette xoxo",
    "Pépère a vu un ORIGNAL sur le bord de la ROUTE!! 🫎 GROS COMME UN CHAR!! on a FAILLI le frapper!! bisous Ginette xo",
    "J'ai ENFIN compris comment mettre des PHOTOS sur le Face Book!! 📸 regarde mon JARDIN!! BEAU HEIN?? bisous Ginette",
    "Ma belle!! j'ai tricoté un BAS DE NOËL pour toi!! 🧦 il est ROUGE avec des FLOCONS!! bisous Ginette xoxo",
    "SEIGNEUR le voisin tond son GAZON à 7h du MATIN!! 😤 un SAMEDI!! y'a du monde qui DORMENT!! bisous Ginette xo",
    "J'ai mis trop de SEL dans la soupe 🧂 mais Pépère dit que c'est BON PAREIL!! il est GENTIL!! bisous Ginette",
    "Ma chouette!! j'ai trouvé des PHOTOS de toi BÉBÉ!! 👶 t'étais dont ben CUTE!! j'ai pleuré UN PEU!! bisous Ginette xoxo",
    "Le FACTEUR m'a apporté un COLIS mais c'est pour le VOISIN!! 📦 j'ai failli L'OUVRIR!! bisous Ginette xo",
    "J'ai essayé de faire un GÂTEAU mais j'ai mis du SEL au lieu du SUCRE 😱😱 c'est PAS BON!! bisous Ginette",
    "Ma belle!! pépère dit que je passe TROP DE TEMPS sur le Face Book!! mais c'est LUI qui regarde la TV 14h PAR JOUR!! 🙄 bisous Ginette xo",
    "J'ai vu que tu t'es COUCHÉE TARD hier!! 😤 c'est PAS BON pour la SANTÉ!! couche-toi à 9h COMME MOI!! bisous Ginette xoxo",
    "DEVINE QUOI!! j'ai appris à faire des SELFIES!! 🤳 mais j'ai le DOIGT devant la caméra à CHAQUE FOIS!! bisous Ginette xo",
    "Ma chouette!! j'ai fait du RAGOÛT DE BOULETTES!! 🍖 y'en a pour UNE ARMÉE!! viens en CHERCHER!! bisous Ginette",
    "Pépère a acheté un POISSON ROUGE 🐠 il l'a appelé MARCEL!! je trouve ça DRÔLE!! bisous Ginette xo",
    "Le MICRO-ONDES fait un bruit BIZARRE 😟 ton grand-père dit que c'est NORMAL mais MOI j'suis pas SÛRE!! bisous Ginette xoxo",
    "Ma belle!! j'ai marché 3000 PAS aujourd'hui!! 🚶‍♀️ mon téléphone me L'A DIT!! c'est-tu BEAUCOUP?? bisous Ginette xo",
    "J'AI PERDU MES CLÉS!! 🔑 elles étaient dans MA POCHE depuis LE DÉBUT!! SEIGNEUR!! bisous Ginette",
    "Ma chouette!! la LAVEUSE fait un bruit de TRACTEUR 🚜 pépère dit de lui donner un COUP!! ça marche PAS!! bisous Ginette xo",
    "J'ai acheté des MOTS CROISÉS au dépanneur!! ✏️ j'en suis au NUMÉRO 47!! PERSONNE peut me battre!! bisous Ginette xoxo",
    "ALLÔ ma belle!! j'ai essayé de t'appeler mais ça dit BOÎTE VOCALE!! t'es-tu CORRECTE?? JE M'INQUIÈTE!! 😟 bisous Ginette xo",
    "Pépère a mis son CHANDAIL À L'ENVERS toute la journée 😂 PERSONNE lui a dit!! bisous Ginette",
    "Ma chouette!! le DÉPANNEUR du coin FERME!! 😢 où je vais acheter mes GRATTEUX maintenant?? bisous Ginette xo",
    "J'ai regardé un FILM D'HORREUR hier soir 😱 j'ai pas DORMI!! c'est la FAUTE à pépère!! bisous Ginette xoxo",
]
